<?LassoScript

// DON'T USE THIS FILE AS A TEMPLATE FOR NEW LANGUAGE FILES!
// use languages/language_template.inc instead

// #1. month names - used for archive page listing

var('aMonths')=Array('January','February','March','April','May','June','July','August','September','October','November','December');

// #2. day names - not used in LB0.7, but may be used later

var('aDays')=Array('Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday');
var('aDays_short')=Array('Mon','Tue','Wed','Thu','Fri','Sat','Sun');

// #3. "emptyString": not needed for English language
// #4. other texts:   not needed for English language
?>
